[package]
name = "example-graceful-shutdown"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { path = "../../axum" }
hyper = { version = "=1.0.0-rc.4", features = ["full"] }
tokio = { version = "1.0", features = ["full"] }
